language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --dev --prefer-source

script:
  - composer test

branches:
  only:
    - master
    - develop

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: 7
